# -*- coding: utf-8 -*-
"""V2_Programa - definições

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KSlaurlXx-f5UDHVIk3bCtAWF7OZmNcW
"""

pip install owlready2

from owlready2 import get_ontology,ThingClass,Restriction

from owlready2 import *

onto = get_ontology("Ontologia_v1.owl").load()

def limpar_nome(entidade):
    return entidade.name.replace("_", " ").lower()

def artigo_de(termo):
    femininos = [
        "bexiga", "traqueia", "faringe", "laringe", "uretra",
        "vesícula", "cavidade", "glândula", "frequência",
        "grande", "pequena", "saliva", "urina"
    ]
    primeira_palavra = termo.split()[0]

    if primeira_palavra in femininos:
        return "da"
    return "do"

def listar_itens(itens):
    if not itens:
        return ""

    if len(itens) == 1:
        return itens[0]

    return ", ".join(itens[:-1]) + " e " + itens[-1]

def obter_termo_descritor(classe):
    for item in classe.is_a:
        if isinstance(item, ThingClass) and item.name != "Thing":
            return limpar_nome(item)
    return "conceito"

def obter_relacao(classe, nome_propriedade):
    valores = []

    for item in classe.is_a:
        if isinstance(item, Restriction):
            if item.property.name == nome_propriedade and hasattr(item, "value"):
                valores.append(limpar_nome(item.value))

    return valores

def gerar_definicao(classe):
    termo = limpar_nome(classe)
    nuclear = obter_termo_descritor(classe)

    sistemas = obter_relacao(classe, "faz_parte_de")
    responsabilidades = obter_relacao(classe, "responsável_por")
    formacoes = obter_relacao(classe, "formado_por")
    producoes = obter_relacao(classe, "produz")
    produzido_por = obter_relacao(classe, "produzido_por")
    armazenamentos = obter_relacao(classe, "armazena")
    transportes = obter_relacao(classe, "transporta")
    participacoes = obter_relacao(classe, "participa_de")
    envia = obter_relacao(classe, "envia")
    recebe = obter_relacao(classe, "recebe")   # se existir

    definicao = nuclear

    if sistemas:
        partes_sistemas = [f"{artigo_de(sistema)} {sistema}" for sistema in sistemas]
        definicao += " " + listar_itens(partes_sistemas)

    # Modelo específico para conjunto anatômico
    if nuclear == "conjunto anatômico" and formacoes:
        definicao += f" formado por {listar_itens(formacoes)}"

    # Modelo específico para líquido
    if nuclear == "líquido":
        if produzido_por:
            definicao += f" produzido por {listar_itens(produzido_por)}"

        if armazenamentos:
            definicao += f" armazenado em {listar_itens(armazenamentos)}"

    # Modelo geral para responsabilidade/função
    if formacoes and nuclear != "conjunto anatômico":
        definicao += f" formado por {listar_itens(formacoes)}"

    if envia:
        definicao += f" que envia {listar_itens(envia)}"

    if recebe:
        definicao += f" que recebe {listar_itens(recebe)}"

    if responsabilidades:
        definicao += f" responsável por {listar_itens(responsabilidades)}"

    # Relações complementares
    if producoes:
        definicao += f" responsável por produzir {listar_itens(producoes)}"

    if armazenamentos and nuclear != "líquido":
        definicao += f" responsável por armazenar {listar_itens(armazenamentos)}"

    if transportes:
        definicao += f" responsável por {listar_itens(transportes)}"

    if participacoes:
        definicao += f" que participa de {listar_itens(participacoes)}"

    definicao += "."

    return f"{termo}: {definicao}"

for classe in onto.classes():
    print(gerar_definicao(classe))

nuclear = obter_termo_descritor(classe)
grupos = {}
for classe in onto.classes():

    nuclear = obter_termo_descritor(classe)

    if nuclear not in grupos:
        grupos[nuclear] = []

    grupos[nuclear].append(gerar_definicao(classe))

for nuclear in sorted(grupos.keys()):

    print(f"\n=== {nuclear.upper()} ===\n")

    for definicao in sorted(grupos[nuclear]):
        print(definicao)